##########################################################
##################  默认共有的配置  #################
##########################################################

###################  默认开发环境  ###################
spring:
  profiles:
    active: dev