##########################################################
##################  开发环境共有的配置  #################
##########################################################

###################  项目启动端口  ###################server:server:
server:
  port: 8088
  context-path: /


spring:

  #datasource config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/oscash?autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456

  #druid config
  druid:
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  #spring mvc config
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

#mybatis config
mybatis:
  type-aliases-package: com.osc.oscashdao.entity
  mapper-locations: classpath:mybatis/**/*.xml
  config-location: classpath:mybatis-config.xml

#common mapper config
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL

#pagehelper plugin config
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  dialect: com.github.pagehelper.dialect.helper.MySqlDialect
  row-bounds-with-count: true




