##########################################################
##################  测试共有的配置  #################
##########################################################

###################  测试开发环境  ###################
spring:
  profiles:
    active: test